[package]
name = "quarterpastmarch"
version = "0.4.1"
authors = ["Mike Moran <mike@houseofmoran.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
askama = "0.9"
itertools = "0.8"
async-std = "1.5"